version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - restore_cache:
          keys:
          - common-v1-dependencies-{{ checksum "common/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - common-v1-dependencies-
      - run: cd common && yarn install
      - save_cache:
          paths:
            - common/node_modules
          key: common-v1-dependencies-{{ checksum "common/package.json" }}

      - restore_cache:
          keys:
          - bubblerserver-v1-dependencies-{{ checksum "bubblerserver/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - bubblerserver-v1-dependencies-
      - run: cd bubblerserver && yarn install
      - save_cache:
          paths:
            - bubblerserver/node_modules
          key: bubblerserver-v1-dependencies-{{ checksum "bubblerserver/package.json" }}

      - restore_cache:
          keys:
          - flowserver-v1-dependencies-{{ checksum "flowserver/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - flowserver-v1-dependencies-
      - run: cd flowserver && yarn install
      - save_cache:
          paths:
            - flowserver/node_modules
          key: flowserver-v1-dependencies-{{ checksum "flowserver/package.json" }}

      - restore_cache:
          keys:
          - logserver-v1-dependencies-{{ checksum "logserver/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - logserver-v1-dependencies-
      - run: cd logserver && yarn install
      - save_cache:
          paths:
            - logserver/node_modules
          key: logserver-v1-dependencies-{{ checksum "logserver/package.json" }}

      - restore_cache:
          keys:
          - temperatureserver-v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - temperatureserver-v1-dependencies-
      - run: cd temperatureserver && yarn install
      - save_cache:
          paths:
            - tempertureserver/node_modules
          key: temperatureserver-v1-dependencies-{{ checksum "temperatureserver/package.json" }}

      - restore_cache:
          keys:
          - volumeserver-v1-dependencies-{{ checksum "volumeserver/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - volumeserver-v1-dependencies-
      - run: cd volumeserver && yarn install
      - save_cache:
          paths:
            - volumeserver/node_modules
          key: volumeserver-v1-dependencies-{{ checksum "volumeserver/package.json" }}

      - run: yarn run test-ci

