version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: cd common
      - restore_cache:
          keys:
          - common-v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - common-v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: common-v1-dependencies-{{ checksum "package.json" }}
      - run: cd ..

      - run: cd logserver
      - restore_cache:
          keys:
          - logserver-v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - logserver-v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: logserver-v1-dependencies-{{ checksum "package.json" }}
      - run: cd ..

      - run: cd temperatureserver
      - restore_cache:
          keys:
          - temperatureserver-v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - temperatureserver-v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: temperatureserver-v1-dependencies-{{ checksum "package.json" }}
      - run: cd ..

      - run: yarn run test-ci

